output:
  output_path: trial
primers:
  primer_file: /home/mahmadi/tb_seqs/primers/primer.bed
samples:
  sample_name: GCA_014884645.1
  sample_path: /home/mahmadi/tb_seqs/genomes/long_read_assemblies/pacbio-RSII/GCA_014884645.1/GCA_014884645.1.fna
simulation:
  R: 1.0e-05
  X: 0
  d: 100
  e: 0
  r: 1.0e-05
  read_cnt: 10000
  read_length_1: 150
  read_length_2: 150
